(export mimes)

(define mimes
  (list->table
   '((".avi"     . "video/x-msvideo")
     (".bz2"     . "application/x-bzip")
     (".class"   . "application/octet-stream")
     (".css"     . "text/css")
     (".dtd"     . "text/xml")
     (".dvi"     . "application/x-dvi")
     (".gif"     . "image/gif")
     (".gz"      . "application/x-gzip")
     (".htm"     . "text/html")
     (".html"    . "text/html")
     (".jpeg"    . "image/jpeg")
     (".jpg"     . "image/jpeg")
     (".js"      . "text/javascript")
     (".m3u"     . "audio/x-mpegurl")
     (".mov"     . "video/quicktime")
     (".mp3"     . "audio/mpeg")
     (".mpeg"    . "video/mpeg")
     (".mpg"     . "video/mpeg")
     (".ogg"     . "application/ogg")
     (".pdf"     . "application/pdf")
     (".png"     . "image/png")
     (".ps"      . "application/postscript")
     (".qt"      . "video/quicktime")
     (".sig"     . "application/pgp-signature")
     (".swf"     . "application/x-shockwave-flash")
     (".tar"     . "application/x-tar")
     (".tar.bz2" . "application/x-bzip-compressed-tar")
     (".tar.gz"  . "application/x-tgz")
     (".tbz"     . "application/x-bzip-compressed-tar")
     (".tgz"     . "application/x-tgz")
     (".torrent" . "application/x-bittorrent")
     (".txt"     . "text/plain")
     (".wav"     . "audio/x-wav")
     (".wax"     . "audio/x-ms-wax")
     (".wma"     . "audio/x-ms-wma")
     (".wmv"     . "video/x-ms-wmv")
     (".xml"     . "text/xml")
     (".zip"     . "application/zip")
     ("default"  . "application/octet-stream"))))
